extern "C" void __vl_pinMode(int pin, int mode);
extern "C" void __vl_digitalWrite(int pin, int value);
extern "C" int __vl_digitalRead(int pin);
extern "C" int __vl_analogRead(int pin);
extern "C" void __vl_delay(unsigned long milliseconds);
extern "C" void __vl_delayMicroseconds(unsigned long microseconds);
extern "C" unsigned long __vl_pulseIn(int pin, int value, unsigned long timeout);
extern "C" unsigned long __vl_millis();
extern "C" unsigned long __vl_micros();
extern "C" void __vl_tone(int pin, int frequency);
extern "C" void __vl_noTone(int pin);
extern "C" void __vl_serialBegin(unsigned long baudRate);
extern "C" void __vl_serialPrint(const char *value);
extern "C" void __vl_serialPrintln(const char *value);
extern "C" void __vl_serialPrintInt(int value);
extern "C" void __vl_serialPrintlnInt(int value);
extern "C" void __vl_serialPrintFloat(double value);
extern "C" void __vl_serialPrintlnFloat(double value);
extern "C" void __vl_serialWrite(int value);
extern "C" int __vl_serialAvailable();
extern "C" int __vl_serialRead();
extern "C" void __vl_wireBegin();
extern "C" void __vl_wireBeginTransmission(int address);
extern "C" int __vl_wireWrite(int value);
extern "C" int __vl_wireEndTransmission();
extern "C" int __vl_wireRequestFrom(int address, int count);
extern "C" int __vl_wireAvailable();
extern "C" int __vl_wireRead();
extern "C" bool __vl_bmp280Begin(int address);
extern "C" double __vl_bmp280ReadTemperature(int address);
extern "C" double __vl_bmp280ReadPressure(int address);
extern "C" bool __vl_lcdBegin(int address, int columns, int rows);
extern "C" void __vl_lcdSetCursor(int address, int column, int row);
extern "C" void __vl_lcdPrint(int address, const char *value);
extern "C" void __vl_lcdPrintInt(int address, int value);
extern "C" void __vl_lcdClear(int address);
extern "C" void __vl_lcdBacklight(int address, bool enabled);
extern "C" bool __vl_dhtBegin(int pin, int type);
extern "C" double __vl_dhtReadTemperature(int pin, int type);
extern "C" double __vl_dhtReadHumidity(int pin, int type);
extern "C" bool __vl_servoAttach(int pin);
extern "C" void __vl_servoWrite(int pin, int angle);
extern "C" void __vl_servoWriteMicroseconds(int pin, int pulseUs);
extern "C" bool __vl_adcBegin(int address, int type);
extern "C" int __vl_adcReadSingleEnded(int address, int channel);
extern "C" double __vl_adcComputeVolts(int address, int raw);
extern "C" void __vl_spiBegin();
extern "C" int __vl_spiTransfer(int value);
extern "C" bool __vl_mcp3008Begin(int chipSelectPin);
extern "C" int __vl_mcp3008Read(int chipSelectPin, int channel);
extern "C" void __vl_wifiMode(int mode);
extern "C" int __vl_wifiBegin(const char *ssid, const char *password);
extern "C" int __vl_wifiStatus();
extern "C" bool __vl_wifiSoftAP(const char *ssid, const char *password);
extern "C" int __vl_wifiScanNetworks();
extern "C" int __vl_wifiRssi();
extern "C" int __vl_wifiRssiForSsid(const char *ssid);
extern "C" bool __vl_wifiInternetAvailable();
extern "C" int __vl_tcpConnect(const char *host, int port);
extern "C" int __vl_tcpPrint(const char *data);
extern "C" int __vl_tcpPrintln(const char *data);
extern "C" int __vl_tcpAvailable();
extern "C" int __vl_tcpRead();
extern "C" void __vl_tcpStop();
extern "C" int __vl_tcpConnected();
extern "C" void __vl_mqttSetServer(const char *host, int port);
extern "C" int __vl_mqttConnect();
extern "C" void __vl_mqttDisconnect();
extern "C" int __vl_mqttConnected();
extern "C" unsigned short __vl_mqttSubscribe(const char *topic, int qos);
extern "C" unsigned short __vl_mqttPublish(const char *topic, int qos, bool retain, const char *payload);
extern "C" int __vl_mqttReadMessage(const char *subscribedTopic, char *topic, int topicMax, char *payload, int payloadMax);
